M48
; DRILL file KiCad 10.0.1 date 2026-05-19T00:43:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-19T00:43:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X115.0Y-91.5
X115.0Y-105.5
X121.0Y-91.5
X121.0Y-105.5
T2
X86.55Y-60.5
X86.55Y-114.5
X121.05Y-60.5
X121.05Y-114.5
M30
